DevOps:
  - changed-files:
    - any-glob-to-any-file: 
      - ".github/**/*"
      - "*.json"
      - "*.config.js"
      - "*.config.ts"
      - ".gitignore"

Frontend:
  - changed-files:
    - any-glob-to-any-file: 
      - "components/**/*"
      - "App.tsx"
      - "index.tsx"
      - "types.ts"
      - "index.css"

Backend:
  - changed-files:
    - any-glob-to-any-file: 
      - "server.js"
      - "services/**/*"
      - "routes/**/*"
      - "swaggers/**/*"

"QA: API":
  - changed-files:
    - any-glob-to-any-file: "features/dashboard/api/**/*"

"QA: GUI":
  - changed-files:
    - any-glob-to-any-file: "features/dashboard/gui/**/*"

"QA: Performance":
  - changed-files:
    - any-glob-to-any-file: "features/dashboard/performance/**/*"

"QA: Framework":
  - changed-files:
    - any-glob-to-any-file: 
      - "features/page_objects/**/*"
      - "features/steps/**/*"
      - "features/support/**/*"
      - "features/environment.py"
      - "behave.ini"
      - "requirements.txt"

documentation:
  - changed-files:
    - any-glob-to-any-file: 
      - "**/*.md"
      - "**/README*"
      - "LICENSE"
